# Generated by Django 3.1.3 on 2020-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201117_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLikeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='answer',
            name='right',
            field=models.BooleanField(default=False, verbose_name='Ответ является правильным'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название тега'),
        ),
    ]
