# Generated by Django 3.1.3 on 2020-11-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201118_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionLikeManager',
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='answer',
            new_name='linked_with',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='question',
            new_name='linked_with',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название тега'),
        ),
    ]
