# Generated by Django 3.1.3 on 2020-11-18 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20201118_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeManager',
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('linked_with', 'user')},
        ),
    ]
