# Generated by Django 3.1.3 on 2020-11-18 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20201118_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='linked_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer', verbose_name='Отмеченный ответ'),
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('linked_with', 'user')},
        ),
    ]
